#!/usr/bin/env bash
# Adds IP address to /etc/hosts
# Check if running on Docker
if grep -q docker /proc/1/cgroup; then
    echo "Configuring hosts file..."
else
    echo "This script is intended to run on Docker."
    exit 1
fi

# Modify hosts file
echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts

echo "Hosts configuration completed."
